// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1BIwCa5t2p3oNKuTCfU590PIXYHDieQ4',
    appId: '1:559441849487:web:b075c3acc76526341454fa',
    messagingSenderId: '559441849487',
    projectId: 'chatapp-9acf1',
    authDomain: 'chatapp-9acf1.firebaseapp.com',
    storageBucket: 'chatapp-9acf1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOETLLq_zlilW80KXZZ51vXLpNcYaxsvU',
    appId: '1:559441849487:android:cccd763b55fc73a01454fa',
    messagingSenderId: '559441849487',
    projectId: 'chatapp-9acf1',
    storageBucket: 'chatapp-9acf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQJyXvwAZK4jyT82iQJocg_JFNRiZTJz0',
    appId: '1:559441849487:ios:57d635554b1823691454fa',
    messagingSenderId: '559441849487',
    projectId: 'chatapp-9acf1',
    storageBucket: 'chatapp-9acf1.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQJyXvwAZK4jyT82iQJocg_JFNRiZTJz0',
    appId: '1:559441849487:ios:83d8ffdc382b29e31454fa',
    messagingSenderId: '559441849487',
    projectId: 'chatapp-9acf1',
    storageBucket: 'chatapp-9acf1.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
